### ISSUE TITLE
[BUG]:  2nd user has full sudo privileges

### ISSUE THREAD

**Issue by nis65** [projectpotos/ansible-role-potos_firstboot#15]
### Description of the bug

I used the following settings for this role:
```
potos_firstboot_local_user_add_with_sudo: true
potos_firstboot_local_user_add_without_sudo: true
potos_firstboot_initial_user_delete_admin_iso_user: false
```
This resulted in two users `admin` and `nick`. This is good, but 
both users have full `sudo` permissions:

```
root@mlc2:/home/nick# egrep -w "nick|admin" /etc/group
adm:x:4:syslog,admin
cdrom:x:24:admin
sudo:x:27:admin,nick
dip:x:30:admin
plugdev:x:46:admin
lxd:x:110:admin
admin:x:1000:
nick:x:1001:
```
I believe `nick` should **not** be member of the `sudo` group.

```
root@mlc2:/home/nick# egrep "admin|sudo" /etc/sudoers | egrep -v "^#"
%admin ALL=(ALL) ALL
%sudo	ALL=(ALL:ALL) ALL
@includedir /etc/sudoers.d
```

### Steps To Reproduce

See above

**Comment by fadnincx** [comment]
@nis65 I think we should probably change the variable nameing to `potos_firstboot_local_user_add` and `potos_firstboot_user_sudo`, because currently no matter what just one user is created. If `potos_firstboot_local_user_add_with_sudo: true` then sudo permissioni is added.

The admin user is always generated with sudo permissions (before ansible) and can either be left or removed with `potos_firstboot_initial_user_delete_admin_iso_user`

**Comment by nis65** [comment]
OK, I was inferring the wrong meaning from the variables. So `./tasks/02_user.yml` starts to make more sense to me than before :smile:. Trying to describe the current behaviour a bit more explicitly:

* there are three boolean vars, but not all 8 possible combinations actually make sense / produce the expected result
* the standard iso install needs a local admin (whose username is defined in `config/config.yml` of `potos-iso-builder`) in the target system. This is ubuntu default installer behaviour. If this user is not wanted any more on the target (e.g. because the target is joined to a domain with sssd), it can be removed (by setting `potos_firstboot_initial_user_delete_admin_iso_user`).
* firstboot adds the possibility to create one additional local user, either with or without `sudo` permissions.

So, assuming we keep the admin user created from the install routine,  we can either
* create no additional local user (i.e. both `potos_firstboot_local_user_add_with_sudo` and `potos_firstboot_local_user_add_without_sudo` are `false`. This is similar to a standard Ubuntu install.
* create an additional user with `sudo` permission, resulting in two admin users.
* create an additional user without `sudo`, resulting in one admin user and one non admin user

If we delete the admin user, we have the same options as above, but we have to take care that there
is at least one sudo account working: Either by setting `potos_firstboot_local_user_add_with_sudo` or by ensuring that e.g. the machine is joined successfully to a domain with `sssd` and there are admin users there (and there are no interlocking dependencies like *you need network to see the domain server to login but you can establish the vpn to see the domain server only after login*)

**Comment by nis65** [comment]
With your @fadnincx variable names, this would be like:

* `potos_firstboot_initial_user_delete_admin_iso_user` keeps name and meaning
* `potos_firstboot_local_user_add`: defines wether a local user is created by `firstboot`.
* `potos_firstboot_local_user_add_with_sudo`: defines whether that user will have `sudo` permissions or not.

We are still 4 possible value combinations of the two latter variables encoding only 3 different use cases, but at least the naming makes clearer what is going on. 

To me, this is good enough. Inventing a new list of "user modes", e.g. `[ 'none', 'with-sudo', 'without-sudo' ]` and setting `potos_firstboot_local_user_add` to one of these values to select the expected result would be nice, but produces more code in the end without really getting more.

But: my target client user configuration needs at least one local group to allow my non-admin users (but physical owners of the devices) e.g. to select a new Wifi connection. I use this group to fine tune `sudo`, `polkit`, `pam`, etc. Now that I have forked this role, I start to believe that at least one initial group (I would call it `owners` or sth like that) should also be part of this role...

Happy for any comments about my resoning...

**Comment by nis65** [comment]
@fadnincx I was looking `tasks/02_user.yml` again and was looking how to implement my group requirement.

Are you ok to define a `potos` group?

Making the group name configurable (i.e. `mlc` for my client) does not scale well across multiple roles (i.e. each role would have to redefine the group name again to make the `sudo`/`polkit`/etc. rules apply to).

Or maybe each role should have its own group and users have to go to as many groups as there are roles, so we would need a list of groups the first boot user should be mapped to.

**Comment by nis65** [comment]
Had another thought about the group question. I guess the simplest and also quite generic way would be the following implementation:

* `potos_firstboot_local_user_add` boolean as before
* `potos_firstboot_local_groups`: List of groups to add to `/etc/groups/`
* `potos_firstboot_local_groups_for_local_user`: List of groups where the added user should be member of. By adding 

  * no group to that list we get a local user without sudo permissions
  * the `sudo` group to that list we get a local user with sudo permissions
  * any other groups can be added to cover my use case.
  
  @fadnincx Does that sound reasonable for you?

**Comment by fadnincx** [comment]
:+1: I think you now understood, what the role currently does.

> Are you ok to define a potos group?

Generally, yes,

> Had another thought about the group question. I guess a simple and quite generic way would be the following implementation:
> 
>     * `potos_firstboot_local_user_add`: boolean as before
> 
>     * `potos_firstboot_local_groups`: List of groups to add to `/etc/groups/`
> 
>     * `potos_firstboot_local_groups_for_local_user`: List of local groups that will be 2ary groups of the local user.

Here we should not forget the variable, if the admin user used to setup everything shall be removed or further exist.
Additionally, this scheme could be extended to multiple predefined users/group/memberships quite easily, if such a requirement appears. However, maybe `potos_firstboot_ask_local_user_add` describes the behavior behind the boolean probably a bit better.

**Comment by nis65** [comment]
Yes of course, sorry for being too brief. `potos_firstboot_initial_user_delete_admin_iso_user` keeps its name and function, so there will be 4 variables (2 booleans and 2 group lists) governing the initial users and and groups.
