### ISSUE TITLE
[BUG]: initrd is not rebuilt in 1st boot

### ISSUE THREAD

**Issue by nis65** [projectpotos/ansible-role-potos_firstboot#16]
### Description of the bug

While I was working on "hibernate" on my potos linux client, I discovered 
that when I hibernate my labtop after first boot, the wake-up does not work
and it boots normally.

The reason is that the initrd needs to have been built while the swap partition
is actually online (I guess). So I propose to add `update-initramfs -u -k all` to
the first boot role.

I tried to find out whether I can inspect the current initramfs to see if that 
change already happened, but was unsuccessful so far (this would be
needed to move this to the hibernate role as unconditionally rebuilding 
the initrd every hour would not make sense).

But on the other hand, I assume that rebuilding the initrd once is not a bad 
thing anyway.

@fadnincx 
* Are you ok with adding this to firstboot?
* I would create an ansible variable so that you can decide in your specs repo if you want this or not.

### Steps To Reproduce

* Install a new potos from an ISO with properly enabled swap partition
* Try to hibernate after the install -> you get a normal boot, not a wake up from hibernation
* run `update-initramfs -u -k all`
* hibernate again
* wake up works now!

**Comment by nis65** [comment]
I solved this currently by adding this `update-initramfs` command to my `potos_firstboot_postcommands` in the specs repo:

~~~
potos_firstboot_postcommands:
  - update-initramfs -u -k all
~~~

Good enough, @fadnincx and close the bug?

**Comment by fadnincx** [comment]
@nis65 
Not sure if this is the best way, but for the moment I'm ok with that solution. If further client appear with that requirement, we should consider to change it to a specific task.

So going to close this bug accordingly.
